AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - 'spec/**/*'
    - 'sound_util.gemspec'

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 170

Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/FormatStringToken:
  Enabled: false
Style/FormatString:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
Style/NilComparison:
  Enabled: false
Style/NumericPredicate:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Lint/Void:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/SymbolProc:
  Enabled: false
